// import debug from "debug";
// const log = debug("app: log");
// debug.enable("*");
// log("Logging is enable");
import { sum } from "./module1";
import phong from "./phong.glsl";
import scene from "./scene.json";
const res = sum(30, 30);
console.log(res);
console.log(phong);
console.log(scene);
console.log("ABC");
